language: julia

os:
  - linux

julia:
  - 1.0

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'import Hamiltonian; joinpath(dirname(pathof(Hamiltonian))); include(joinpath("docs","make.jl"))'
