language: julia

os:
  - linux

julia:
  - 1.0

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("Hamiltonian")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'using Pkg; Pkg.add("Documenter"); import Hamiltonian; joinpath(dirname(pathof(Hamiltonian))); include(joinpath("docs","make.jl"))'
