language: julia

os:
  - linux

julia:
  - 1.0

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'using Pkg; cd(Pkg.dir("Hamiltonian")); include(joinpath("docs", "make.jl"))'
